apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-privileged
  labels:
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - litmus
  resources:
  - securitycontextconstraints
  verbs:
  - use
