apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-privileged-binding
  labels:
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-privileged
subjects:
- kind: ServiceAccount
  name: litmus-admin
  namespace: litmus